---
# https://docs.travis-ci.com/user/languages/go
sudo: false
language: go
go:
- 1.5
env:
- GIMME_OS=linux GIMME_ARCH=amd64
- GIMME_OS=darwin GIMME_ARCH=amd64
install:
- go get -d -v ./...
script:
- go build -v -o terraform-provisioner-ansible
- tar czvf terraform-provisioner-ansible_${TRAVIS_TAG}_${GIMME_OS}_${GIMME_ARCH}.tar.gz terraform-provisioner-ansible
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  file: terraform-provisioner-ansible_*
  file_glob: true
  on:
    repo: joaocc/jonmorehouse--terraform-provisioner-ansible
    all_branches: true
    tags: true
